--
-- AnimalMod
--
-- @authors: Dirk Peeters / Jengske_BE / international-modding
-- @version: 0.01 beta
-- @website: http://jengske.github.io/AnimalMod/
-- @date:    2015
-- @history: 
-- @devTeam :
-- Dirk Peeters: lua, 3d model & animation, xml
-- 
-- Copyright (C) 2011 - 2015 international-modding Dev Team
-- 
AnimalMod = {};
